In [12]:
#!pip install tensorflow

In [13]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [14]:
import pandas as pd
import numpy as np

x = [-3,  31,  -11,  4,  0,  22, -2, -5, -25, -14]
y = [ -2,   32,   -10,   5,  1,   23,  -1,  -4, -24,  -13]

X_train = np.array(x).reshape(-1, 1)
y_train = np.array(y)

print(X_train.shape, y_train.shape)

(10, 1) (10,)


In [15]:
X_train

array([[ -3],
       [ 31],
       [-11],
       [  4],
       [  0],
       [ 22],
       [ -2],
       [ -5],
       [-25],
       [-14]])

In [16]:
y_train

array([ -2,  32, -10,   5,   1,  23,  -1,  -4, -24, -13])

In [17]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=1, activation='linear', input_dim=1))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [22]:
model.fit(X_train, y_train, epochs=10, verbose=2)

Epoch 1/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 3ms/epoch - 3ms/step
Epoch 2/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 992us/epoch - 992us/step
Epoch 3/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 1ms/epoch - 1ms/step
Epoch 4/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 3ms/epoch - 3ms/step
Epoch 5/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 5ms/epoch - 5ms/step
Epoch 6/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 5ms/epoch - 5ms/step
Epoch 7/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 3ms/epoch - 3ms/step
Epoch 8/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 3ms/epoch - 3ms/step
Epoch 9/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 2ms/epoch - 2ms/step
Epoch 10/10
1/1 - 0s - loss: 5.6819e-12 - mae: 1.7107e-06 - 1ms/epoch - 1ms/step


In [8]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.9951326]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.99765193], dtype=float32)>]

In [23]:
model.predict([[11], [12], [13]])

array([[11.999998],
       [12.999997],
       [13.999997]], dtype=float32)