In [1]:
# 필수 라이브러리
import pandas as pd
import numpy as np
import random
import tensorflow as tf

# 랜덤 시드 고정
SEED=12
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)  
print("시드 고정: ", SEED)

시드 고정:  12


In [2]:
data = pd.read_csv('data/train.csv')
data.shape

(5497, 14)

In [3]:
data

index  quality  fixed acidity  volatile acidity  citric acid  \
0         0        5            5.6             0.695         0.06   
1         1        5            8.8             0.610         0.14   
2         2        5            7.9             0.210         0.39   
3         3        6            7.0             0.210         0.31   
4         4        6            7.8             0.400         0.26   
...     ...      ...            ...               ...          ...   
5492   5492        5            7.7             0.150         0.29   
5493   5493        6            6.3             0.180         0.36   
5494   5494        7            7.8             0.150         0.34   
5495   5495        5            6.6             0.410         0.31   
5496   5496        6            7.0             0.350         0.17   

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0   
1                2.4      0.067                 10.0                  42.0   
2                2.0      0.057                 21.0                 138.0   
3                6.0      0.046                 29.0                 108.0   
4                9.5      0.059                 32.0                 178.0   
...              ...        ...                  ...                   ...   
5492             1.3      0.029                 10.0                  64.0   
5493             1.2      0.034                 26.0                 111.0   
5494             1.1      0.035                 31.0                  93.0   
5495             1.6      0.042                 18.0                 101.0   
5496             1.1      0.049                  7.0                 119.0   

      density    pH  sulphates  alcohol   type  
0     0.99432  3.44       0.44     10.2  white  
1     0.99690  3.19       0.59      9.5    red  
2     0.99176  3.05       0.52     10.9  white  
3     0.99390  3.26       0.50     10.8  white  
4     0.99550  3.04       0.43     10.9  white  
...       ...   ...        ...      ...    ...  
5492  0.99320  3.35       0.39     10.1  white  
5493  0.99074  3.16       0.51     11.0  white  
5494  0.99096  3.07       0.72     11.3  white  
5495  0.99195  3.13       0.41     10.5  white  
5496  0.99297  3.13       0.36      9.7  white  

[5497 rows x 14 columns]

In [4]:
data['quality']

0       5
1       5
2       5
3       6
4       6
       ..
5492    5
5493    6
5494    7
5495    5
5496    6
Name: quality, Length: 5497, dtype: int64

In [5]:
data['type']

0       white
1         red
2       white
3       white
4       white
        ...  
5492    white
5493    white
5494    white
5495    white
5496    white
Name: type, Length: 5497, dtype: object

In [6]:
data['type'] = np.where(data['type'] == 'white', 1, 0).astype('int')
data['type'].value_counts()

1    4159
0    1338
Name: type, dtype: int64

In [7]:
data['quality'].value_counts()

6    2416
5    1788
7     924
4     186
8     152
3      26
9       5
Name: quality, dtype: int64

In [8]:
from tensorflow.keras.utils import to_categorical
y_data = to_categorical(data.loc[:, 'quality'] - 3)
y_data

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
X_data = data.loc[:, 'fixed acidity':]
X_data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               5.6             0.695         0.06             6.8      0.042   
1               8.8             0.610         0.14             2.4      0.067   
2               7.9             0.210         0.39             2.0      0.057   
3               7.0             0.210         0.31             6.0      0.046   
4               7.8             0.400         0.26             9.5      0.059   
...             ...               ...          ...             ...        ...   
5492            7.7             0.150         0.29             1.3      0.029   
5493            6.3             0.180         0.36             1.2      0.034   
5494            7.8             0.150         0.34             1.1      0.035   
5495            6.6             0.410         0.31             1.6      0.042   
5496            7.0             0.350         0.17             1.1      0.049   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     9.0                  84.0  0.99432  3.44       0.44   
1                    10.0                  42.0  0.99690  3.19       0.59   
2                    21.0                 138.0  0.99176  3.05       0.52   
3                    29.0                 108.0  0.99390  3.26       0.50   
4                    32.0                 178.0  0.99550  3.04       0.43   
...                   ...                   ...      ...   ...        ...   
5492                 10.0                  64.0  0.99320  3.35       0.39   
5493                 26.0                 111.0  0.99074  3.16       0.51   
5494                 31.0                  93.0  0.99096  3.07       0.72   
5495                 18.0                 101.0  0.99195  3.13       0.41   
5496                  7.0                 119.0  0.99297  3.13       0.36   

      alcohol  type  
0        10.2     1  
1         9.5     0  
2        10.9     1  
3        10.8     1  
4        10.9     1  
...       ...   ...  
5492     10.1     1  
5493     11.0     1  
5494     11.3     1  
5495     10.5     1  
5496      9.7     1  

[5497 rows x 12 columns]

In [10]:
X_data.shape

(5497, 12)

In [11]:
# min_max스케일링
# 피처 스케일링
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_data)
X_data_scaled = scaler.fit_transform(X_data)

In [12]:
print(X_data_scaled.shape, y_data.shape)

(5497, 12) (5497, 7)


In [13]:
# train/test data분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data_scaled, y_data, 
                                                    test_size=0.2, 
                                                    shuffle=True, 
                                                    random_state=100)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(4397, 12) (4397, 7)
(1100, 12) (1100, 7)


In [14]:
y_train.shape[1]

7

In [15]:
# 모델생성
# 심층 신경망 모델
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
def build_model(train_data, train_target):
    model = Sequential()
    model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
   # model.add(Dropout(0.2))
    model.add(Dense(64, activation='relu'))
    # model.add(Dropout(0.1))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(y_train.shape[1], activation='softmax'))

    adam = tf.keras.optimizers.Adam(learning_rate=0.001)
#     model.compile(optimizer='adam', loss='categorical_crossentropy', 
#                 metrics=['acc', 'mae'])
    
    model.compile(optimizer= adam, loss='categorical_crossentropy', 
                metrics=['acc', 'mae'])
    
    return model
model = build_model(X_train, y_train)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1664      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 10)                330       
                                                                 
 dense_4 (Dense)             (None, 7)                 77        
                                                                 
Total params: 12,407
Trainable params: 12,407
Non-trainable params: 0
_________________________________________________________________


In [24]:
# fit시켜보자
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='acc',  patience=10)

X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.1, 
                                            shuffle=True, random_state=200)

history = model.fit(X_tr, y_tr, 
                    batch_size=12, 
                    epochs=200,
                    validation_data=(X_val, y_val),
                    callbacks=[early_stopping],                    
                    verbose=2)

Epoch 1/200
330/330 - 0s - loss: 1.0166 - acc: 0.5577 - mae: 0.1606 - val_loss: 1.0642 - val_acc: 0.5568 - val_mae: 0.1625 - 259ms/epoch - 785us/step
Epoch 2/200
330/330 - 0s - loss: 1.0073 - acc: 0.5696 - mae: 0.1599 - val_loss: 1.0632 - val_acc: 0.5295 - val_mae: 0.1602 - 256ms/epoch - 776us/step
Epoch 3/200
330/330 - 0s - loss: 1.0000 - acc: 0.5676 - mae: 0.1594 - val_loss: 1.0597 - val_acc: 0.5591 - val_mae: 0.1581 - 332ms/epoch - 1ms/step
Epoch 4/200
330/330 - 0s - loss: 1.0005 - acc: 0.5770 - mae: 0.1590 - val_loss: 1.0762 - val_acc: 0.5568 - val_mae: 0.1643 - 324ms/epoch - 980us/step
Epoch 5/200
330/330 - 0s - loss: 1.0051 - acc: 0.5696 - mae: 0.1594 - val_loss: 1.0502 - val_acc: 0.5386 - val_mae: 0.1623 - 339ms/epoch - 1ms/step
Epoch 6/200
330/330 - 0s - loss: 0.9978 - acc: 0.5762 - mae: 0.1588 - val_loss: 1.0437 - val_acc: 0.5795 - val_mae: 0.1599 - 278ms/epoch - 842us/step
Epoch 7/200
330/330 - 0s - loss: 0.9937 - acc: 0.5757 - mae: 0.1587 - val_loss: 1.0593 - val_acc: 0.5545

Epoch 56/200
330/330 - 0s - loss: 0.8528 - acc: 0.6358 - mae: 0.1399 - val_loss: 1.0677 - val_acc: 0.5568 - val_mae: 0.1532 - 303ms/epoch - 918us/step
Epoch 57/200
330/330 - 0s - loss: 0.8512 - acc: 0.6343 - mae: 0.1400 - val_loss: 1.0851 - val_acc: 0.5750 - val_mae: 0.1530 - 271ms/epoch - 822us/step
Epoch 58/200
330/330 - 0s - loss: 0.8522 - acc: 0.6328 - mae: 0.1402 - val_loss: 1.0638 - val_acc: 0.5886 - val_mae: 0.1469 - 293ms/epoch - 888us/step
Epoch 59/200
330/330 - 0s - loss: 0.8428 - acc: 0.6346 - mae: 0.1390 - val_loss: 1.1154 - val_acc: 0.5636 - val_mae: 0.1498 - 278ms/epoch - 843us/step
Epoch 60/200
330/330 - 0s - loss: 0.8400 - acc: 0.6389 - mae: 0.1385 - val_loss: 1.0694 - val_acc: 0.5795 - val_mae: 0.1497 - 264ms/epoch - 800us/step
Epoch 61/200
330/330 - 0s - loss: 0.8370 - acc: 0.6391 - mae: 0.1385 - val_loss: 1.0576 - val_acc: 0.5750 - val_mae: 0.1469 - 245ms/epoch - 742us/step
Epoch 62/200
330/330 - 0s - loss: 0.8355 - acc: 0.6351 - mae: 0.1384 - val_loss: 1.0918 - val_

Epoch 111/200
330/330 - 1s - loss: 0.6507 - acc: 0.7255 - mae: 0.1093 - val_loss: 1.2382 - val_acc: 0.5773 - val_mae: 0.1366 - 541ms/epoch - 2ms/step
Epoch 112/200
330/330 - 0s - loss: 0.6329 - acc: 0.7420 - mae: 0.1069 - val_loss: 1.2293 - val_acc: 0.5750 - val_mae: 0.1373 - 399ms/epoch - 1ms/step
Epoch 113/200
330/330 - 0s - loss: 0.6313 - acc: 0.7321 - mae: 0.1071 - val_loss: 1.2229 - val_acc: 0.5818 - val_mae: 0.1347 - 401ms/epoch - 1ms/step
Epoch 114/200
330/330 - 0s - loss: 0.6427 - acc: 0.7329 - mae: 0.1068 - val_loss: 1.1960 - val_acc: 0.6182 - val_mae: 0.1341 - 250ms/epoch - 756us/step
Epoch 115/200
330/330 - 0s - loss: 0.6304 - acc: 0.7354 - mae: 0.1061 - val_loss: 1.2003 - val_acc: 0.5773 - val_mae: 0.1369 - 250ms/epoch - 759us/step
Epoch 116/200
330/330 - 0s - loss: 0.6250 - acc: 0.7319 - mae: 0.1057 - val_loss: 1.1804 - val_acc: 0.5955 - val_mae: 0.1326 - 244ms/epoch - 740us/step
Epoch 117/200
330/330 - 0s - loss: 0.6287 - acc: 0.7412 - mae: 0.1053 - val_loss: 1.2676 - val

Epoch 166/200
330/330 - 0s - loss: 0.4652 - acc: 0.8137 - mae: 0.0789 - val_loss: 1.5504 - val_acc: 0.5795 - val_mae: 0.1297 - 443ms/epoch - 1ms/step
Epoch 167/200
330/330 - 0s - loss: 0.4737 - acc: 0.8127 - mae: 0.0791 - val_loss: 1.5510 - val_acc: 0.6114 - val_mae: 0.1286 - 409ms/epoch - 1ms/step
Epoch 168/200
330/330 - 1s - loss: 0.4556 - acc: 0.8196 - mae: 0.0775 - val_loss: 1.5048 - val_acc: 0.5864 - val_mae: 0.1257 - 538ms/epoch - 2ms/step
Epoch 169/200
330/330 - 0s - loss: 0.4643 - acc: 0.8158 - mae: 0.0781 - val_loss: 1.4806 - val_acc: 0.5886 - val_mae: 0.1307 - 438ms/epoch - 1ms/step
Epoch 170/200
330/330 - 0s - loss: 0.4566 - acc: 0.8160 - mae: 0.0779 - val_loss: 1.5014 - val_acc: 0.6091 - val_mae: 0.1234 - 428ms/epoch - 1ms/step
Epoch 171/200
330/330 - 0s - loss: 0.4413 - acc: 0.8208 - mae: 0.0755 - val_loss: 1.5356 - val_acc: 0.5841 - val_mae: 0.1302 - 408ms/epoch - 1ms/step
Epoch 172/200
330/330 - 0s - loss: 0.4532 - acc: 0.8198 - mae: 0.0765 - val_loss: 1.5462 - val_acc: 

In [25]:
# test데이터로 예측하여 정확도 체크해볼 것.
loss, acc, _ = model.evaluate(X_val, y_val)
print('loss>> ', loss)
print('acc>> ', acc)

14/14 [==============================] - 0s 1ms/step - loss: 1.6803 - acc: 0.5977 - mae: 0.1224
loss>>  1.6803290843963623
acc>>  0.5977272987365723


In [18]:
# test 데이터에 대한 예측값 정리
y_pred_proba = model.predict(X_test)
y_pred_proba[:5]

array([[3.9908962e-04, 1.7439916e-03, 2.2113238e-02, 4.4795895e-01,
        4.6489593e-01, 6.2681712e-02, 2.0717790e-04],
       [5.3232320e-04, 2.8902534e-03, 6.0239252e-02, 6.1683446e-01,
        2.7107009e-01, 4.8269745e-02, 1.6388914e-04],
       [1.3265494e-03, 9.4166556e-03, 1.1224672e-01, 6.1695427e-01,
        2.3096366e-01, 2.8906524e-02, 1.8567046e-04],
       [8.5712934e-04, 6.7214039e-03, 1.1710508e-01, 6.2170535e-01,
        2.1984883e-01, 3.3434939e-02, 3.2735476e-04],
       [7.9604232e-04, 1.1616648e-02, 5.9126616e-01, 3.7732700e-01,
        1.8006152e-02, 9.8795316e-04, 9.1759219e-08]], dtype=float32)

In [19]:
y_pred_label = np.argmax(y_pred_proba, axis=-1) + 3
y_pred_label[:5]

array([7, 6, 6, 6, 5], dtype=int64)

In [20]:
y_pred_label.shape

(1100,)

In [21]:
y_test.shape

(1100, 7)

In [22]:
y_test2 = np.argmax(y_test, axis=-1) + 3
y_test2

array([8, 5, 5, ..., 6, 7, 8], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

print(accuracy_score(y_test2, y_pred_label))

0.5554545454545454
